export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const AUTH_VERIFY_CODE = "AUTH_VERIFY_CODE";
export const AUTH_ONBOARD_DATA = "AUTH_ONBOARD_DATA";
export const AUTH_SIGNUP_DATA = "AUTH_SIGNUP_DATA";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ADD_CO6S = "AUTH_ADD_CO6S";
export const AUTH_SET_ACCESS_TOKEN = "AUTH_SET_ACCESS_TOKEN";